In [ ]:
import numpy as np

In [ ]:
# Example matrices for demonstration
matrix1 = np.random.randint(0, 10, (5, 5))
matrix2 = np.random.randint(0, 10, (5, 5))

In [ ]:
print(matrix1)

[[4 7 5 0 6]
 [0 2 7 3 3]
 [0 0 1 7 8]
 [9 6 8 1 7]
 [1 6 3 0 6]]


In [ ]:
print(matrix2)

[[4 7 6 7 0]
 [9 4 0 7 4]
 [7 1 2 4 1]
 [3 9 8 9 4]
 [1 0 8 9 6]]


In [ ]:
# Add the matrices
addition_result = matrix1 + matrix2
print("Matrix Addition:")
print(addition_result)

Matrix Addition:
[[ 8 14 11  7  6]
 [ 9  6  7 10  7]
 [ 7  1  3 11  9]
 [12 15 16 10 11]
 [ 2  6 11  9 12]]


In [ ]:
# Subtract the matrices
subtraction_result = matrix1 - matrix2
print("Matrix Subtraction:")
print(subtraction_result)

Matrix Subtraction:
[[ 0  0 -1 -7  6]
 [-9 -2  7 -4 -1]
 [-7 -1 -1  3  7]
 [ 6 -3  0 -8  3]
 [ 0  6 -5 -9  0]]


In [ ]:
# Scalar Multiplication
scalar = 2
scalar_multiplication = scalar * matrix1
print("Matrix Scalar Multiplication:")
print(scalar_multiplication)

Matrix Scalar Multiplication:
[[ 8 14 10  0 12]
 [ 0  4 14  6  6]
 [ 0  0  2 14 16]
 [18 12 16  2 14]
 [ 2 12  6  0 12]]


In [ ]:
# Transpose of a matrix
transpose = np.transpose(matrix1)
print("Matrix Transpose:")
print(transpose)

Matrix Transpose:
[[4 0 0 9 1]
 [7 2 0 6 6]
 [5 7 1 8 3]
 [0 3 7 1 0]
 [6 3 8 7 6]]


In [ ]:
# Covariance of a matrix
cov_matrix = np.cov(matrix1)
print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[ 7.3   0.25 -4.35  5.9   6.65]
 [ 0.25  6.5   1.   -0.25  0.75]
 [-4.35  1.   15.7  -7.05 -0.05]
 [ 5.9  -0.25 -7.05  9.7   2.95]
 [ 6.65  0.75 -0.05  2.95  7.7 ]]
